export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="container mx-auto px-4 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            🎉 d
          </h1>
          <p className="text-xl text-gray-600 mb-8">
            Generated by OpsAI - Your custom business application is ready!
          </p>
          <div className="bg-white rounded-lg shadow-lg p-8 max-w-2xl mx-auto">
            <h2 className="text-2xl font-semibold mb-4">Welcome to your app!</h2>
            <p className="text-gray-600 mb-6">
              This is your generated E-commerce with the following features:
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
              
            </div>
            <div className="space-y-4">
              <a 
                href="/admin" 
                className="inline-block bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition-colors"
              >
                🔧 Open Admin Panel
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}