export const emailTemplates = {
  
  'task_overdue': {
    subject: 'Alert: overdue_tasks',
    html: `
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .header { background-color: #f8f9fa; padding: 20px; border-bottom: 2px solid #dee2e6; }
    .content { padding: 20px; }
    .priority-high { color: #dc3545; font-weight: bold; }
    .priority-medium { color: #fd7e14; font-weight: bold; }
    .priority-low { color: #28a745; }
    .footer { background-color: #f8f9fa; padding: 10px; font-size: 12px; color: #6c757d; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚨 Alert: overdue_tasks</h1>
  </div>
  <div class="content">
    <p><strong>Description:</strong> Alert when tasks are overdue</p>
    <p><strong>Priority:</strong> <span class="priority-{{priority}}">{{priority}}</span></p>
    <p><strong>Triggered at:</strong> {{timestamp}}</p>
    <p><strong>Details:</strong></p>
    <ul>
      {{#each conditions}}
      <li>{{field}} {{operator}} {{value}}</li>
      {{/each}}
    </ul>
    <p><strong>Data:</strong></p>
    <pre>{{alertData}}</pre>
  </div>
  <div class="footer">
    <p>This alert was generated by Comprehensive Test Platform</p>
  </div>
</body>
</html>`,
    text: `🚨 ALERT: overdue_tasks

Description: Alert when tasks are overdue
Priority: {{priority}}
Triggered at: {{timestamp}}

Conditions:
- task.dueDate less_than now()
- task.status not_equals completed

Data: {{alertData}}

---
Generated by Comprehensive Test Platform`
  },
  
  'budget_exceeded': {
    subject: 'Alert: project_budget_exceeded',
    html: `
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .header { background-color: #f8f9fa; padding: 20px; border-bottom: 2px solid #dee2e6; }
    .content { padding: 20px; }
    .priority-high { color: #dc3545; font-weight: bold; }
    .priority-medium { color: #fd7e14; font-weight: bold; }
    .priority-low { color: #28a745; }
    .footer { background-color: #f8f9fa; padding: 10px; font-size: 12px; color: #6c757d; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚨 Alert: project_budget_exceeded</h1>
  </div>
  <div class="content">
    <p><strong>Description:</strong> Alert when project budget is exceeded</p>
    <p><strong>Priority:</strong> <span class="priority-{{priority}}">{{priority}}</span></p>
    <p><strong>Triggered at:</strong> {{timestamp}}</p>
    <p><strong>Details:</strong></p>
    <ul>
      {{#each conditions}}
      <li>{{field}} {{operator}} {{value}}</li>
      {{/each}}
    </ul>
    <p><strong>Data:</strong></p>
    <pre>{{alertData}}</pre>
  </div>
  <div class="footer">
    <p>This alert was generated by Comprehensive Test Platform</p>
  </div>
</body>
</html>`,
    text: `🚨 ALERT: project_budget_exceeded

Description: Alert when project budget is exceeded
Priority: {{priority}}
Triggered at: {{timestamp}}

Conditions:
- project.actualCost greater_than {{project.budget}}

Data: {{alertData}}

---
Generated by Comprehensive Test Platform`
  }
};

export const slackTemplates = {
  default: {
    blocks: [
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: '*Alert Triggered*\n{{description}}'
        }
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: '*Rule:*\n{{ruleName}}'
          },
          {
            type: 'mrkdwn',
            text: '*Priority:*\n{{priority}}'
          },
          {
            type: 'mrkdwn',
            text: '*Time:*\n{{timestamp}}'
          }
        ]
      }
    ]
  }
};

export const webhookTemplates = {
  default: {
    event: 'alert.triggered',
    data: {
      rule: '{{ruleName}}',
      description: '{{description}}',
      priority: '{{priority}}',
      timestamp: '{{timestamp}}',
      data: '{{alertData}}'
    }
  }
};
