'use client'

import { useState } from 'react'

export default function AdminPage() {
  const [user] = useState({
    email: 'admin@example.com',
    name: 'Admin User'
  })

  const stats = [
    { title: 'Total Records', value: '1,234', icon: '📊' },
    { title: 'Active Users', value: '89', icon: '👥' },
    { title: 'Data Models', value: '0', icon: '🗄️' },
    { title: 'Integrations', value: '3', icon: '🔗' }
  ]

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200">
        <div className="px-6 py-4">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">d - Admin</h1>
              <p className="text-gray-600">Generated by OpsAI</p>
            </div>
            <div className="flex items-center space-x-2">
              <div className="text-right">
                <div className="text-sm font-medium text-gray-900">{user.name}</div>
                <div className="text-xs text-gray-500">{user.email}</div>
              </div>
              <div className="w-8 h-8 bg-blue-600 rounded-full flex items-center justify-center">
                <span className="text-white text-sm font-medium">A</span>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="px-6 py-8">
        <div className="max-w-7xl mx-auto">
          {/* Welcome */}
          <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-8">
            <h2 className="text-lg font-semibold text-green-900 mb-2">
              🚀 Your App is Live!
            </h2>
            <p className="text-green-800">
              This admin panel is running on a separate port from the onboarding app. 
              In a real deployment, this would be connected to your database and integrations.
            </p>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
            {stats.map((stat, index) => (
              <div key={index} className="bg-white rounded-lg shadow p-6">
                <div className="flex items-center">
                  <div className="text-2xl mr-4">{stat.icon}</div>
                  <div>
                    <p className="text-sm font-medium text-gray-600">{stat.title}</p>
                    <p className="text-2xl font-bold text-gray-900">{stat.value}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Data Models */}
          <div className="bg-white rounded-lg shadow mb-8">
            <div className="px-6 py-4 border-b border-gray-200">
              <h3 className="text-lg font-semibold text-gray-900">Data Models</h3>
            </div>
            <div className="p-6">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                
              </div>
            </div>
          </div>

          {/* Integrations */}
          <div className="bg-white rounded-lg shadow">
            <div className="px-6 py-4 border-b border-gray-200">
              <h3 className="text-lg font-semibold text-gray-900">Connected Integrations</h3>
            </div>
            <div className="p-6">
              
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                
                <div className="border border-gray-200 rounded-lg p-4">
                  <div className="flex items-center justify-between">
                    <h4 className="font-semibold text-gray-900">Shopify</h4>
                    <span className="text-xs bg-green-100 text-green-800 px-2 py-1 rounded-full">
                      Connected
                    </span>
                  </div>
                  <p className="text-sm text-gray-600 mt-2">Shopify integration for data sync</p>
                </div>
                
                <div className="border border-gray-200 rounded-lg p-4">
                  <div className="flex items-center justify-between">
                    <h4 className="font-semibold text-gray-900">Stripe</h4>
                    <span className="text-xs bg-green-100 text-green-800 px-2 py-1 rounded-full">
                      Connected
                    </span>
                  </div>
                  <p className="text-sm text-gray-600 mt-2">Stripe integration for data sync</p>
                </div>
                
                <div className="border border-gray-200 rounded-lg p-4">
                  <div className="flex items-center justify-between">
                    <h4 className="font-semibold text-gray-900">Google Analytics</h4>
                    <span className="text-xs bg-green-100 text-green-800 px-2 py-1 rounded-full">
                      Connected
                    </span>
                  </div>
                  <p className="text-sm text-gray-600 mt-2">Google Analytics integration for data sync</p>
                </div>
                
              </div>
              
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}