# Demo Application Configuration
app:
  name: demo-saas-app
  displayName: Demo SaaS Application
  description: A demonstration SaaS application with core features
  version: 1.0.0
  author: OpsAI Platform
  license: MIT

database:
  type: postgresql
  entities:
    - name: user
      displayName: Users
      description: Application users
      fields:
        id:
          type: string
          required: true
          unique: true
          ui:
            widget: input
            label: ID
        email:
          type: string
          required: true
          unique: true
          validation:
            pattern: ^[^\s@]+@[^\s@]+\.[^\s@]+$
          ui:
            widget: input
            label: Email
            placeholder: user@example.com
        name:
          type: string
          required: true
          ui:
            widget: input
            label: Full Name
        role:
          type: string
          required: true
          default: user
          validation:
            enum:
              - admin
              - user
              - viewer
          ui:
            widget: select
            label: Role
            options:
              - label: Administrator
                value: admin
              - label: User
                value: user
              - label: Viewer
                value: viewer
        isActive:
          type: boolean
          default: true
          ui:
            widget: checkbox
            label: Active
        createdAt:
          type: date
          required: true
          ui:
            widget: date
            label: Created At
        updatedAt:
          type: date
          required: true
          ui:
            widget: date
            label: Updated At
      permissions:
        create:
          - admin
        read:
          - admin
          - user
          - viewer
        update:
          - admin
          - user
        delete:
          - admin

    - name: project
      displayName: Projects
      description: User projects
      fields:
        id:
          type: string
          required: true
          unique: true
          ui:
            widget: input
            label: ID
        name:
          type: string
          required: true
          ui:
            widget: input
            label: Project Name
        description:
          type: text
          ui:
            widget: textarea
            label: Description
        ownerId:
          type: string
          required: true
          ui:
            widget: select
            label: Owner
        status:
          type: string
          default: draft
          validation:
            enum:
              - draft
              - active
              - completed
              - archived
          ui:
            widget: select
            label: Status
            options:
              - label: Draft
                value: draft
              - label: Active
                value: active
              - label: Completed
                value: completed
              - label: Archived
                value: archived
        createdAt:
          type: date
          required: true
          ui:
            widget: date
            label: Created At
        updatedAt:
          type: date
          required: true
          ui:
            widget: date
            label: Updated At
      permissions:
        create:
          - admin
          - user
        read:
          - admin
          - user
          - viewer
        update:
          - admin
          - user
        delete:
          - admin

integrations:
  - name: email-service
    type: rest
    config:
      baseUrl: https://api.emailservice.com
      timeout: 30000
    endpoints:
      - name: send-email
        method: POST
        path: /v1/send
        authentication:
          type: api-key
          config:
            header: X-API-Key

workflows:
  - name: user-onboarding
    displayName: User Onboarding
    description: Onboard new users with welcome email
    trigger:
      type: event
      config:
        event: user.created
    steps:
      - name: send-welcome-email
        type: api-call
        config:
          integration: email-service
          endpoint: send-email
          template: welcome-email
        retry:
          attempts: 3
          delay: 5000

ui:
  theme: default
  pages:
    - name: dashboard
      path: /
      title: Dashboard
      description: Main dashboard
      layout: default
      components:
        - type: stats
          config:
            title: Overview
            stats:
              - label: Total Users
                value: "{{count('user')}}"
              - label: Active Projects
                value: "{{count('project', {status: 'active'})}}"
      permissions:
        - admin
        - user
        - viewer

    - name: users
      path: /users
      title: Users
      description: Manage application users
      layout: list
      components:
        - type: table
          config:
            entity: user
            columns:
              - name
              - email
              - role
              - isActive
              - createdAt
            actions:
              - create
              - edit
              - delete
      permissions:
        - admin

    - name: projects
      path: /projects
      title: Projects
      description: Manage projects
      layout: list
      components:
        - type: table
          config:
            entity: project
            columns:
              - name
              - description
              - status
              - createdAt
              - updatedAt
            actions:
              - create
              - edit
              - delete
      permissions:
        - admin
        - user

features:
  authentication: true
  multiTenancy: false
  fileUpload: true
  notifications: true
  analytics: false
  cron: false