export const emailTemplates = {
  
  'high_budget_alert': {
    subject: 'Alert: high_budget_project',
    html: `
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .header { background-color: #f8f9fa; padding: 20px; border-bottom: 2px solid #dee2e6; }
    .content { padding: 20px; }
    .priority-high { color: #dc3545; font-weight: bold; }
    .priority-medium { color: #fd7e14; font-weight: bold; }
    .priority-low { color: #28a745; }
    .footer { background-color: #f8f9fa; padding: 10px; font-size: 12px; color: #6c757d; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚨 Alert: high_budget_project</h1>
  </div>
  <div class="content">
    <p><strong>Description:</strong> Alert when project budget exceeds threshold</p>
    <p><strong>Priority:</strong> <span class="priority-{{priority}}">{{priority}}</span></p>
    <p><strong>Triggered at:</strong> {{timestamp}}</p>
    <p><strong>Details:</strong></p>
    <ul>
      {{#each conditions}}
      <li>{{field}} {{operator}} {{value}}</li>
      {{/each}}
    </ul>
    <p><strong>Data:</strong></p>
    <pre>{{alertData}}</pre>
  </div>
  <div class="footer">
    <p>This alert was generated by TechCorp Platform</p>
  </div>
</body>
</html>`,
    text: `🚨 ALERT: high_budget_project

Description: Alert when project budget exceeds threshold
Priority: {{priority}}
Triggered at: {{timestamp}}

Conditions:
- project.budget greater_than 100000

Data: {{alertData}}

---
Generated by TechCorp Platform`
  },
  
  'task_overdue': {
    subject: 'Alert: task_overdue',
    html: `
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .header { background-color: #f8f9fa; padding: 20px; border-bottom: 2px solid #dee2e6; }
    .content { padding: 20px; }
    .priority-high { color: #dc3545; font-weight: bold; }
    .priority-medium { color: #fd7e14; font-weight: bold; }
    .priority-low { color: #28a745; }
    .footer { background-color: #f8f9fa; padding: 10px; font-size: 12px; color: #6c757d; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚨 Alert: task_overdue</h1>
  </div>
  <div class="content">
    <p><strong>Description:</strong> Alert when task is overdue</p>
    <p><strong>Priority:</strong> <span class="priority-{{priority}}">{{priority}}</span></p>
    <p><strong>Triggered at:</strong> {{timestamp}}</p>
    <p><strong>Details:</strong></p>
    <ul>
      {{#each conditions}}
      <li>{{field}} {{operator}} {{value}}</li>
      {{/each}}
    </ul>
    <p><strong>Data:</strong></p>
    <pre>{{alertData}}</pre>
  </div>
  <div class="footer">
    <p>This alert was generated by TechCorp Platform</p>
  </div>
</body>
</html>`,
    text: `🚨 ALERT: task_overdue

Description: Alert when task is overdue
Priority: {{priority}}
Triggered at: {{timestamp}}

Conditions:
- task.dueDate less_than now()
- task.status not_equals completed

Data: {{alertData}}

---
Generated by TechCorp Platform`
  },
  
  'subscription_renewal': {
    subject: 'Alert: subscription_expiring',
    html: `
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .header { background-color: #f8f9fa; padding: 20px; border-bottom: 2px solid #dee2e6; }
    .content { padding: 20px; }
    .priority-high { color: #dc3545; font-weight: bold; }
    .priority-medium { color: #fd7e14; font-weight: bold; }
    .priority-low { color: #28a745; }
    .footer { background-color: #f8f9fa; padding: 10px; font-size: 12px; color: #6c757d; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚨 Alert: subscription_expiring</h1>
  </div>
  <div class="content">
    <p><strong>Description:</strong> Alert when subscription is expiring soon</p>
    <p><strong>Priority:</strong> <span class="priority-{{priority}}">{{priority}}</span></p>
    <p><strong>Triggered at:</strong> {{timestamp}}</p>
    <p><strong>Details:</strong></p>
    <ul>
      {{#each conditions}}
      <li>{{field}} {{operator}} {{value}}</li>
      {{/each}}
    </ul>
    <p><strong>Data:</strong></p>
    <pre>{{alertData}}</pre>
  </div>
  <div class="footer">
    <p>This alert was generated by TechCorp Platform</p>
  </div>
</body>
</html>`,
    text: `🚨 ALERT: subscription_expiring

Description: Alert when subscription is expiring soon
Priority: {{priority}}
Triggered at: {{timestamp}}

Conditions:
- organization.subscriptionEndDate less_than now() + 30 days

Data: {{alertData}}

---
Generated by TechCorp Platform`
  }
};

export const slackTemplates = {
  default: {
    blocks: [
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: '*Alert Triggered*\n{{description}}'
        }
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: '*Rule:*\n{{ruleName}}'
          },
          {
            type: 'mrkdwn',
            text: '*Priority:*\n{{priority}}'
          },
          {
            type: 'mrkdwn',
            text: '*Time:*\n{{timestamp}}'
          }
        ]
      }
    ]
  }
};

export const webhookTemplates = {
  default: {
    event: 'alert.triggered',
    data: {
      rule: '{{ruleName}}',
      description: '{{description}}',
      priority: '{{priority}}',
      timestamp: '{{timestamp}}',
      data: '{{alertData}}'
    }
  }
};
