[build]
  command = "pnpm run build"
  publish = "dist"
  [environment]
    NODE_ENV = "production"
    PORT = "3000"
    DATABASE_URL = "${DATABASE_URL}"
    JWT_SECRET = "${JWT_SECRET}"
    GUESTY_API_CLIENT_ID = "${GUESTY_API_CLIENT_ID}"
    GUESTY_API_CLIENT_SECRET = "${GUESTY_API_CLIENT_SECRET}"
    CLIENT_ID = "${CLIENT_ID}"
    CLIENT_SECRET = "${CLIENT_SECRET}"
    NETLIFY_SITE_ID = "${NETLIFY_SITE_ID}"
    NETLIFY_AUTH_TOKEN = "${NETLIFY_AUTH_TOKEN}"
[functions]
  directory = "netlify/functions"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
