'use client'

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { 
  Users, 
  ShoppingCart, 
  DollarSign, 
  Activity,
  Settings,
  Database,
  BarChart3,
  LogOut,
  Bell,
  Search,
  Menu
} from 'lucide-react'

export default function DemoAdminPage() {
  const [user, setUser] = useState({
    email: 'admin@example.com',
    name: 'Admin User',
    role: 'Administrator'
  })

  const stats = [
    {
      title: 'Total Users',
      value: '2,849',
      change: '+12%',
      icon: Users,
      color: 'text-blue-600'
    },
    {
      title: 'Sales',
      value: '$45,231',
      change: '+8%',
      icon: DollarSign,
      color: 'text-green-600'
    },
    {
      title: 'Orders',
      value: '1,234',
      change: '+23%',
      icon: ShoppingCart,
      color: 'text-purple-600'
    },
    {
      title: 'Active Users',
      value: '573',
      change: '+5%',
      icon: Activity,
      color: 'text-orange-600'
    }
  ]

  const recentOrders = [
    { id: '#001', customer: 'John Doe', amount: '$299.00', status: 'Completed', date: '2024-01-15' },
    { id: '#002', customer: 'Jane Smith', amount: '$159.00', status: 'Processing', date: '2024-01-15' },
    { id: '#003', customer: 'Bob Johnson', amount: '$89.00', status: 'Pending', date: '2024-01-14' },
    { id: '#004', customer: 'Alice Brown', amount: '$199.00', status: 'Completed', date: '2024-01-14' },
  ]

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 sticky top-0 z-50">
        <div className="px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Button variant="ghost" size="sm">
                <Menu className="h-5 w-5" />
              </Button>
              <h1 className="text-xl font-semibold text-gray-900">Demo Admin Panel</h1>
              <Badge variant="secondary" className="bg-green-100 text-green-800">
                🚀 Generated by OpsAI
              </Badge>
            </div>
            
            <div className="flex items-center space-x-4">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
                <input
                  type="text"
                  placeholder="Search..."
                  className="pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <Button variant="ghost" size="sm">
                <Bell className="h-5 w-5" />
              </Button>
              <div className="flex items-center space-x-2">
                <div className="text-right">
                  <div className="text-sm font-medium text-gray-900">{user.name}</div>
                  <div className="text-xs text-gray-500">{user.email}</div>
                </div>
                <div className="w-8 h-8 bg-blue-600 rounded-full flex items-center justify-center">
                  <span className="text-white text-sm font-medium">
                    {user.name.charAt(0)}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="px-6 py-8">
        <div className="max-w-7xl mx-auto">
          {/* Welcome Section */}
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-2">
              Welcome to your Admin Dashboard! 🎉
            </h2>
            <p className="text-gray-600">
              This is a demo of what your generated admin panel looks like. Your actual app would have real data and functionality.
            </p>
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
            {stats.map((stat, index) => {
              const Icon = stat.icon
              return (
                <Card key={index} className="hover:shadow-lg transition-shadow">
                  <CardContent className="p-6">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-sm font-medium text-gray-600">{stat.title}</p>
                        <p className="text-2xl font-bold text-gray-900">{stat.value}</p>
                        <p className="text-sm text-green-600">{stat.change} from last month</p>
                      </div>
                      <div className={`p-3 rounded-full bg-gray-100 ${stat.color}`}>
                        <Icon className="h-6 w-6" />
                      </div>
                    </div>
                  </CardContent>
                </Card>
              )
            })}
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Recent Orders */}
            <Card>
              <CardHeader>
                <CardTitle>Recent Orders</CardTitle>
                <CardDescription>Latest customer orders and their status</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {recentOrders.map((order) => (
                    <div key={order.id} className="flex items-center justify-between p-4 border rounded-lg">
                      <div>
                        <div className="font-medium text-gray-900">{order.customer}</div>
                        <div className="text-sm text-gray-500">
                          {order.id} • {order.date}
                        </div>
                      </div>
                      <div className="text-right">
                        <div className="font-medium text-gray-900">{order.amount}</div>
                        <Badge 
                          variant={
                            order.status === 'Completed' ? 'default' :
                            order.status === 'Processing' ? 'secondary' : 
                            'outline'
                          }
                          className="text-xs"
                        >
                          {order.status}
                        </Badge>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Quick Actions */}
            <Card>
              <CardHeader>
                <CardTitle>Quick Actions</CardTitle>
                <CardDescription>Common admin tasks and settings</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-4">
                  <Button variant="outline" className="h-20 flex flex-col items-center gap-2">
                    <Users className="h-6 w-6" />
                    <span className="text-sm">Manage Users</span>
                  </Button>
                  <Button variant="outline" className="h-20 flex flex-col items-center gap-2">
                    <ShoppingCart className="h-6 w-6" />
                    <span className="text-sm">View Orders</span>
                  </Button>
                  <Button variant="outline" className="h-20 flex flex-col items-center gap-2">
                    <BarChart3 className="h-6 w-6" />
                    <span className="text-sm">Analytics</span>
                  </Button>
                  <Button variant="outline" className="h-20 flex flex-col items-center gap-2">
                    <Settings className="h-6 w-6" />
                    <span className="text-sm">Settings</span>
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Info Banner */}
          <Card className="mt-8 border-blue-200 bg-blue-50">
            <CardContent className="p-6">
              <div className="flex items-start space-x-4">
                <div className="p-2 bg-blue-100 rounded-lg">
                  <Database className="h-6 w-6 text-blue-600" />
                </div>
                <div>
                  <h3 className="font-semibold text-blue-900 mb-2">
                    🎉 This is your generated admin panel!
                  </h3>
                  <p className="text-blue-800 mb-4">
                    In the real generated app, this would be connected to your actual database and integrations. 
                    You would have full CRUD operations, real-time data, authentication, and all the features 
                    you configured during onboarding.
                  </p>
                  <div className="space-y-2 text-sm text-blue-700">
                    <div>• Database: PostgreSQL with Supabase</div>
                    <div>• Authentication: Email/password with session management</div>
                    <div>• API: RESTful endpoints with TypeScript</div>
                    <div>• UI: React with Tailwind CSS</div>
                    <div>• Integrations: Connected to your business tools</div>
                  </div>
                  <Button className="mt-4" size="sm">
                    Deploy to Production
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}