
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_captcha_enabled = false
security_captcha_secret = ""
security_update_password_require_reauthentication = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false





[db]
port = 54322
major_version = 15

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"
