export const emailTemplates = {
  
  'reservation_confirmed': {
    subject: 'Alert: reservation_confirmed',
    html: `
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .header { background-color: #f8f9fa; padding: 20px; border-bottom: 2px solid #dee2e6; }
    .content { padding: 20px; }
    .priority-high { color: #dc3545; font-weight: bold; }
    .priority-medium { color: #fd7e14; font-weight: bold; }
    .priority-low { color: #28a745; }
    .footer { background-color: #f8f9fa; padding: 10px; font-size: 12px; color: #6c757d; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚨 Alert: reservation_confirmed</h1>
  </div>
  <div class="content">
    <p><strong>Description:</strong> Alert when reservation is confirmed</p>
    <p><strong>Priority:</strong> <span class="priority-{{priority}}">{{priority}}</span></p>
    <p><strong>Triggered at:</strong> {{timestamp}}</p>
    <p><strong>Details:</strong></p>
    <ul>
      {{#each conditions}}
      <li>{{field}} {{operator}} {{value}}</li>
      {{/each}}
    </ul>
    <p><strong>Data:</strong></p>
    <pre>{{alertData}}</pre>
  </div>
  <div class="footer">
    <p>This alert was generated by Line Properties</p>
  </div>
</body>
</html>`,
    text: `🚨 ALERT: reservation_confirmed

Description: Alert when reservation is confirmed
Priority: {{priority}}
Triggered at: {{timestamp}}

Conditions:
- status equals confirmed

Data: {{alertData}}

---
Generated by Line Properties`
  },
  
  'property_available': {
    subject: 'Alert: property_availability_change',
    html: `
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .header { background-color: #f8f9fa; padding: 20px; border-bottom: 2px solid #dee2e6; }
    .content { padding: 20px; }
    .priority-high { color: #dc3545; font-weight: bold; }
    .priority-medium { color: #fd7e14; font-weight: bold; }
    .priority-low { color: #28a745; }
    .footer { background-color: #f8f9fa; padding: 10px; font-size: 12px; color: #6c757d; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚨 Alert: property_availability_change</h1>
  </div>
  <div class="content">
    <p><strong>Description:</strong> Alert when property becomes available</p>
    <p><strong>Priority:</strong> <span class="priority-{{priority}}">{{priority}}</span></p>
    <p><strong>Triggered at:</strong> {{timestamp}}</p>
    <p><strong>Details:</strong></p>
    <ul>
      {{#each conditions}}
      <li>{{field}} {{operator}} {{value}}</li>
      {{/each}}
    </ul>
    <p><strong>Data:</strong></p>
    <pre>{{alertData}}</pre>
  </div>
  <div class="footer">
    <p>This alert was generated by Line Properties</p>
  </div>
</body>
</html>`,
    text: `🚨 ALERT: property_availability_change

Description: Alert when property becomes available
Priority: {{priority}}
Triggered at: {{timestamp}}

Conditions:
- status equals available

Data: {{alertData}}

---
Generated by Line Properties`
  },
  
  'token_expiry_warning': {
    subject: 'Alert: api_token_expiring',
    html: `
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .header { background-color: #f8f9fa; padding: 20px; border-bottom: 2px solid #dee2e6; }
    .content { padding: 20px; }
    .priority-high { color: #dc3545; font-weight: bold; }
    .priority-medium { color: #fd7e14; font-weight: bold; }
    .priority-low { color: #28a745; }
    .footer { background-color: #f8f9fa; padding: 10px; font-size: 12px; color: #6c757d; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚨 Alert: api_token_expiring</h1>
  </div>
  <div class="content">
    <p><strong>Description:</strong> Alert when Guesty API token expires soon</p>
    <p><strong>Priority:</strong> <span class="priority-{{priority}}">{{priority}}</span></p>
    <p><strong>Triggered at:</strong> {{timestamp}}</p>
    <p><strong>Details:</strong></p>
    <ul>
      {{#each conditions}}
      <li>{{field}} {{operator}} {{value}}</li>
      {{/each}}
    </ul>
    <p><strong>Data:</strong></p>
    <pre>{{alertData}}</pre>
  </div>
  <div class="footer">
    <p>This alert was generated by Line Properties</p>
  </div>
</body>
</html>`,
    text: `🚨 ALERT: api_token_expiring

Description: Alert when Guesty API token expires soon
Priority: {{priority}}
Triggered at: {{timestamp}}

Conditions:
- token_expires_at less_than now() + 24 hours

Data: {{alertData}}

---
Generated by Line Properties`
  }
};

export const slackTemplates = {
  default: {
    blocks: [
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: '*Alert Triggered*\n{{description}}'
        }
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: '*Rule:*\n{{ruleName}}'
          },
          {
            type: 'mrkdwn',
            text: '*Priority:*\n{{priority}}'
          },
          {
            type: 'mrkdwn',
            text: '*Time:*\n{{timestamp}}'
          }
        ]
      }
    ]
  }
};

export const webhookTemplates = {
  default: {
    event: 'alert.triggered',
    data: {
      rule: '{{ruleName}}',
      description: '{{description}}',
      priority: '{{priority}}',
      timestamp: '{{timestamp}}',
      data: '{{alertData}}'
    }
  }
};
